
const SET_HISTORY = "SET_HISTORY";
const SET_STEPNUMBER = "SET_STEPNUMBER";
const SET_X = "SET_X";
const SET_MOV = "SET_MOV";
const SET_WIN_SQUARE = "SET_WIN_SQUARE";
const SET_CHOICE = "SET_CHOICE"
